POST /mgmt/shared/cloud-failover/declare HTTP/1.1
Host: "${host}"
Content-Type: application/json
Authorization: Basic "${auth}"
Content-Length: 176

{
    "class": "Cloud_Failover",
    "environment": "gcp",
    "externalStorage": {
        "scopingTags": {
            "f5_cloud_failover_label": "${label}"
        }
    }
}